// Curated list of common disposable / throwaway email providers.
// Kept intentionally compact — covers the vast majority of signup abuse
// without needing an external service. Add domains as needed.
export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  '0-mail.com','027168.com','10minutemail.com','10minutemail.net','20minutemail.com',
  '2prong.com','30minutemail.com','33mail.com','3d-painting.com','4warding.com',
  '4warding.net','60minutemail.com','7tags.com','9ox.net','a-bc.net',
  'anonbox.net','anonymbox.com','antichef.com','antichef.net','antispam.de',
  'armyspy.com','baxomale.ht.cx','beefmilk.com','binkmail.com','bio-muesli.net',
  'bobmail.info','bofthew.com','brefmail.com','bsnow.net','bugmenot.com',
  'bumpymail.com','casualdx.com','chogmail.com','choicemail1.com','cool.fr.nf',
  'courriel.fr.nf','cust.in','cuvox.de','dacoolest.com','dandikmail.com',
  'deadaddress.com','despam.it','despammed.com','devnullmail.com','dfgh.net',
  'digitalsanctuary.com','discardmail.com','discardmail.de','disposableaddress.com',
  'disposableemailaddresses.com','disposableinbox.com','dispose.it','dispostable.com',
  'dodgeit.com','dodgit.com','dodgit.org','dontreg.com','dontsendmespam.de',
  'drdrb.net','dump-email.info','dumpandjunk.com','dumpyemail.com','einrot.com',
  'e4ward.com','email60.com','emailgo.de','emailias.com','emaillime.com',
  'emailmiser.com','emailsensei.com','emailtemporanea.com','emailtemporanea.net',
  'emailtmp.com','emailwarden.com','emailx.at.hm','emailxfer.com','emeil.in',
  'emeil.ir','emz.net','enterto.com','ephemail.net','explodemail.com',
  'fakeinbox.com','fakeinformation.com','fastacura.com','fastchevy.com','fastchrysler.com',
  'fastkawasaki.com','fastmazda.com','fastmitsubishi.com','fastnissan.com','fastsubaru.com',
  'fastsuzuki.com','fasttoyota.com','fastyamaha.com','filzmail.com','fizmail.com',
  'fr33mail.info','frapmail.com','friendlymail.co.uk','fux0ringduh.com','garliclife.com',
  'get1mail.com','get2mail.fr','getairmail.com','getmails.eu','ghosttexter.de',
  'girlsundertheinfluence.com','gishpuppy.com','gowikibooks.com','grr.la','guerillamail.biz',
  'guerillamail.com','guerrillamail.biz','guerrillamail.com','guerrillamail.de','guerrillamail.info',
  'guerrillamail.net','guerrillamail.org','guerrillamailblock.com','h.mintemail.com','hacccc.com',
  'harakirimail.com','hatespam.org','herp.in','hidemail.de','hidzz.com',
  'hmamail.com','hopemail.biz','hotpop.com','hulapla.de','imails.info',
  'inbax.tk','inbox.si','inboxalias.com','inboxbear.com','inboxclean.com',
  'incognitomail.com','incognitomail.net','incognitomail.org','ipoo.org','irish2me.com',
  'jetable.com','jetable.fr.nf','jetable.net','jetable.org','jnxjn.com',
  'junk1e.com','kaspop.com','keepmymail.com','killmail.com','killmail.net',
  'klassmaster.com','kulturbetrieb.info','kurzepost.de','lawlita.com','letthemeatspam.com',
  'lhsdv.com','lifebyfood.com','link2mail.net','litedrop.com','lookugly.com',
  'lopl.co.cc','lortemail.dk','lr78.com','maboard.com','mail-filter.com',
  'mail-temporaire.fr','mail.by','mail.mezimages.net','mail4trash.com','mail666.ru',
  'mailbidon.com','mailbiz.biz','mailblocks.com','mailcatch.com','maildrop.cc',
  'mailexpire.com','mailfa.tk','mailin8r.com','mailinater.com','mailinator.com',
  'mailinator.net','mailinator.org','mailinator2.com','mailincubator.com','mailismagic.com',
  'mailme.lv','mailmetrash.com','mailmoat.com','mailnator.com','mailnesia.com',
  'mailnull.com','mailscrap.com','mailshell.com','mailsiphon.com','mailtemp.info',
  'mailtome.de','mailtothis.com','mailtrash.net','mailtv.net','mailzilla.com',
  'mailzilla.org','makemetheking.com','manybrain.com','mbx.cc','meltmail.com',
  'messagebeamer.de','mierdamail.com','mintemail.com','moburl.com','moncourrier.fr.nf',
  'monemail.fr.nf','monmail.fr.nf','msa.minsmail.com','mt2009.com','mycard.net.ua',
  'mycleaninbox.net','myemailboxy.com','mymail-in.net','mypacks.net','mypartyclip.de',
  'myphantomemail.com','myspaceinc.com','myspaceinc.net','myspaceinc.org','myspamless.com',
  'mytempemail.com','mytempmail.com','mytrashmail.com','neomailbox.com','nepwk.com',
  'nervmich.net','nervtmich.net','netmails.com','netmails.net','netzidiot.de',
  'neverbox.com','no-spam.ws','nobulk.com','noclickemail.com','nogmailspam.info',
  'nomail.xl.cx','nomail2me.com','nomorespamemails.com','nospam.ze.tc','nospam4.us',
  'nospamfor.us','nospammail.net','notmailinator.com','nowhere.org','nurfuerspam.de',
  'nus.edu.sg','objectmail.com','obobbo.com','oneoffemail.com','onewaymail.com',
  'online.ms','ordinaryamerican.net','otherinbox.com','ovpn.to','owlpic.com',
  'pancakemail.com','pcusers.otherinbox.com','pjjkp.com','plexolan.de','poofy.org',
  'pookmail.com','privacy.net','privatdemail.net','proxymail.eu','prtnx.com',
  'putthisinyourspamdatabase.com','qq.com','quickinbox.com','rcpt.at','recode.me',
  'recursor.net','reallymymail.com','regbypass.com','regbypass.comsafe-mail.net','rejectmail.com',
  'reliable-mail.com','rhyta.com','rmqkr.net','royal.net','rppkn.com',
  'rtrtr.com','s0ny.net','safe-mail.net','safersignup.de','safetymail.info',
  'safetypost.de','sandelf.de','saynotospams.com','selfdestructingmail.com','sendspamhere.com',
  'shieldedmail.com','shiftmail.com','shitmail.me','shitware.nl','shortmail.net',
  'sibmail.com','skeefmail.com','slaskpost.se','smashmail.de','smellfear.com',
  'snakemail.com','sneakemail.com','snkmail.com','sofimail.com','sofort-mail.de',
  'sogetthis.com','soodonims.com','spam4.me','spamavert.com','spambob.com',
  'spambob.net','spambob.org','spambog.com','spambog.de','spambog.ru',
  'spambox.info','spambox.us','spamcannon.com','spamcannon.net','spamcero.com',
  'spamcorptastic.com','spamcowboy.com','spamcowboy.net','spamcowboy.org','spamday.com',
  'spamex.com','spamfree.eu','spamfree24.com','spamfree24.de','spamfree24.eu',
  'spamfree24.info','spamfree24.net','spamfree24.org','spamgoes.in','spamgourmet.com',
  'spamgourmet.net','spamgourmet.org','spamherelots.com','spamhereplease.com','spamhole.com',
  'spamify.com','spaminator.de','spamkill.info','spaml.com','spaml.de',
  'spammotel.com','spamobox.com','spamoff.de','spamsalad.in','spamslicer.com',
  'spamspot.com','spamthis.co.uk','spamthisplease.com','spamtroll.net','speed.1s.fr',
  'spoofmail.de','stuffmail.de','super-auswahl.de','supergreatmail.com','supermailer.jp',
  'superrito.com','superstachel.de','suremail.info','talkinator.com','teewars.org',
  'teleworm.com','teleworm.us','tempalias.com','tempe-mail.com','tempemail.biz',
  'tempemail.com','tempemail.net','tempinbox.co.uk','tempinbox.com','tempmail.eu',
  'tempmail.it','tempmail2.com','tempmaildemo.com','tempmailer.com','tempmailer.de',
  'tempomail.fr','temporarily.de','temporarioemail.com.br','temporaryemail.net','temporaryforwarding.com',
  'temporaryinbox.com','temporarymailaddress.com','tempthe.net','thankyou2010.com','thecloudindex.com',
  'thisisnotmyrealemail.com','throwawayemailaddresses.com','tilien.com','tmail.ws','tmailinator.com',
  'toomail.biz','topranklist.de','tradermail.info','trash-amil.com','trash-mail.at',
  'trash-mail.com','trash-mail.de','trash2009.com','trashdevil.com','trashemail.de',
  'trashmail.at','trashmail.com','trashmail.de','trashmail.me','trashmail.net',
  'trashmail.org','trashmail.ws','trashymail.com','trashymail.net','trbvm.com',
  'trialmail.de','trillianpro.com','turual.com','twinmail.de','tyldd.com',
  'uggsrock.com','umail.net','upliftnow.com','uplipht.com','uroid.com',
  'us.af','venompen.com','veryrealemail.com','viditag.com','viewcastmedia.com',
  'viewcastmedia.net','viewcastmedia.org','vpn.st','vsimcard.com','vubby.com',
  'wasteland.rfc822.org','webemail.me','weg-werf-email.de','wegwerf-emails.de','wegwerfadresse.de',
  'wegwerfemail.com','wegwerfemail.de','wegwerfmail.de','wegwerfmail.info','wegwerfmail.net',
  'wegwerfmail.org','wh4f.org','whyspam.me','willhackforfood.biz','willselfdestruct.com',
  'winemaven.info','wronghead.com','wuzup.net','wuzupmail.net','www.e4ward.com',
  'www.mailinator.com','wwwnew.eu','x.ip6.li','xagloo.com','xemaps.com',
  'xents.com','xmaily.com','xoxy.net','yep.it','yogamaven.com',
  'yopmail.com','yopmail.fr','yopmail.net','ypmail.webarnak.fr.eu.org','yuurok.com',
  'zehnminuten.de','zehnminutenmail.de','zippymail.info','zoemail.net','zoemail.org',
  'zomg.info','tempail.com','moakt.com','emailondeck.com','fakemailgenerator.com',
  'getnada.com','nada.email','mohmal.com','tmailor.com','burnermail.io',
  'trashinbox.com','tempinbox.xyz','dropmail.me','spam4.me','disbox.net',
  'anonaddy.me','tempmail.ninja','emailfake.com','tempmailo.com','edu.sg',
]);

/** Returns true when the email's domain looks like a throwaway provider. */
export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf('@');
  if (at < 0) return false;
  const domain = email.slice(at + 1).toLowerCase().trim();
  if (!domain) return false;
  if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) return true;
  // Also block subdomains of disposable providers (e.g. sub.mailinator.com).
  const parts = domain.split('.');
  for (let i = 1; i < parts.length - 1; i++) {
    const suffix = parts.slice(i).join('.');
    if (DISPOSABLE_EMAIL_DOMAINS.has(suffix)) return true;
  }
  return false;
}
