import { createFileRoute } from "@tanstack/react-router";
import { PageShell, H2, P, UL } from "@/components/PageShell";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Risk Disclaimer — Jenvu" },
      { name: "description", content: "Important risk disclosure for users of Jenvu AI trading analysis, signals and the voice agent. Read before trading." },
      { property: "og:title", content: "Risk Disclaimer — Jenvu" },
      { property: "og:url", content: "https://jenvu.com/disclaimer" },
    ],
    links: [{ rel: "canonical", href: "https://jenvu.com/disclaimer" }],
  }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <PageShell
      eyebrow="Legal"
      title="Risk Disclaimer"
      intro="Trading carries substantial risk. Please read this disclosure carefully before using any analysis, alert, or signal produced by Jenvu."
    >
      <section className="space-y-3">
        <H2>1. Not financial advice</H2>
        <P>Jenvu is an educational and analytical research tool. Nothing on jenvu.com, the voice agent, the signal desk, articles, or any alert constitutes investment advice, a recommendation to buy or sell, or a solicitation. We are not a registered investment adviser, broker-dealer, or financial planner in any jurisdiction.</P>
      </section>

      <section className="space-y-3">
        <H2>2. Trading involves substantial risk</H2>
        <UL>
          <li>Leveraged trading in gold (XAU/USD), CFDs and futures can result in losses exceeding your initial deposit.</li>
          <li>Past performance — whether of Jenvu setups, model backtests, or other traders — does not guarantee future results.</li>
          <li>You can lose all the money you allocate to trading. Never trade with capital you cannot afford to lose.</li>
        </UL>
      </section>

      <section className="space-y-3">
        <H2>3. AI limitations</H2>
        <P>Jenvu's analysis is generated by AI models combined with public market data feeds. Outputs may contain errors, stale data, false positives, hallucinated price levels, or incorrect bias. Always verify entry, stop-loss, and take-profit levels against your own broker's chart before acting.</P>
      </section>

      <section className="space-y-3">
        <H2>4. You are responsible for your trades</H2>
        <P>Any decision to enter, modify, or exit a position is solely yours. By using Jenvu you acknowledge that you alone are responsible for risk management, position sizing, broker selection, slippage, spread, swap costs, taxes, and outcomes.</P>
      </section>

      <section className="space-y-3">
        <H2>5. No guarantee of accuracy or availability</H2>
        <P>We strive for accuracy but make no warranty regarding correctness, timeliness, or completeness of any signal, price, or commentary. The service may be delayed, interrupted, or unavailable at any time. Realtime data may differ from your broker's quotes.</P>
      </section>

      <section className="space-y-3">
        <H2>6. Regulatory notice</H2>
        <P>Some products discussed on Jenvu (spot gold, XAU CFDs, gold futures) may be restricted or prohibited in your jurisdiction. It is your responsibility to ensure trading complies with all applicable laws and regulations.</P>
      </section>

      <section className="space-y-3">
        <H2>7. Hypothetical performance</H2>
        <P>Where Jenvu publishes win rates, R:R averages, or grade statistics, these are derived from logged setups and are hypothetical or illustrative. They do not reflect actual money traded by real users, may exclude slippage and fees, and benefit from hindsight. Hypothetical performance has many inherent limitations.</P>
      </section>

      <section className="space-y-3">
        <H2>8. Acknowledgement</H2>
        <P>By using Jenvu you confirm that you have read, understood, and accepted this disclaimer in full, and that you are using the service at your own risk.</P>
      </section>
    </PageShell>
  );
}
