INSERT INTO public.insight_topics (keyword, angle, category, priority) VALUES
('gold price forecast', 'What actually moves the gold price week to week: real yields, DXY, central-bank demand and how to read the levels', 'Market Structure', 10),
('gold price prediction 2026', 'Scenario framework for 2026 gold rather than a single number: bull, base and bear drivers', 'Market Structure', 10),
('gold price uk', 'How UK traders should read gold in GBP: XAU/GBP, spread betting vs CFD, FCA context and London session behaviour', 'Market Structure', 10),
('gold price today', 'Daily framework for reading todays gold move: London open, New York open, data releases', 'Market Structure', 9),
('xauusd', 'Complete XAUUSD trading guide: spec, spreads, sessions, volatility profile and ICT levels that matter', 'Education', 10),
('gold trading strategy', 'A rules-based gold strategy built on ICT killzones, order blocks and liquidity sweeps', 'Education', 10),
('smart money concepts', 'Smart money concepts explained properly: order blocks, FVGs, liquidity, market structure shifts', 'Education', 10),
('ict trading strategy', 'ICT strategy for gold: killzones, judas swing, optimal trade entry, risk model', 'Education', 10),
('london session gold trading', 'Why the London killzone produces the cleanest gold setups and how to trade it', 'Education', 9),
('best time to trade gold uk', 'Session-by-session gold volatility for UK time zones and where the edge sits', 'Education', 9),
('gold news', 'How to trade gold around scheduled news: CPI, NFP, Fed, ECB and BoE decisions', 'News', 9),
('gold price and interest rates', 'The real-yield mechanism: why rate expectations, not headlines, set golds direction', 'Macro', 8),
('ecb interest rate decision', 'How ECB decisions move XAU/EUR and European gold pricing', 'Macro', 8),
('gold price after fed decision', 'Fed-day playbook for gold: pre-positioning, the whipsaw, and the trend that follows', 'Macro', 8),
('xau eur', 'Trading gold in euros: XAU/EUR mechanics, EUR risk overlay and Frankfurt open behaviour', 'Market Structure', 9),
('gold spread betting uk', 'Gold spread betting vs CFD for UK traders: costs, tax treatment basics, risk controls', 'Education', 8),
('prop firm gold trading', 'Passing a prop challenge on gold: drawdown rules, position sizing and session selection', 'Education', 9),
('mt5 gold signals', 'How to evaluate gold signal services and what a verifiable track record looks like', 'Education', 8),
('gold etf vs physical gold', 'ETF, futures, CFD or physical: which gold exposure suits which objective', 'Investing', 7),
('is gold a good investment now', 'A framework for sizing gold in a European portfolio instead of a yes or no answer', 'Investing', 7),
('gold investment 2026', 'Allocation thinking for 2026: gold as a hedge against real-rate and currency risk', 'Investing', 7),
('central bank gold buying', 'Why central-bank accumulation changed golds floor and what to watch', 'Macro', 8),
('bitcoin price prediction', 'A driver-based way to think about bitcoin cycles instead of price targets', 'Crypto', 8),
('bitcoin vs gold safe haven', 'Correlation, drawdowns and behaviour in stress: how bitcoin and gold really differ', 'Crypto', 8),
('gold vs bitcoin', 'Head to head on volatility, liquidity, custody and hedging role', 'Crypto', 7),
('crypto regulation europe mica', 'What MiCA means for European crypto traders in practice', 'Crypto', 7),
('crypto news today', 'How to filter crypto news flow into tradable information', 'Crypto', 6),
('goldpreis prognose', 'LANG:de | Was den Goldpreis wirklich bewegt: Realzinsen, Dollar, Notenbanknachfrage', 'Market Structure', 10),
('bitcoin kurs prognose', 'LANG:de | Treiberbasierte Einordnung des Bitcoin-Zyklus statt Kursziele', 'Crypto', 8),
('gold traden lernen', 'LANG:de | ICT und Smart Money Concepts fuer XAUUSD: Killzones, Order Blocks, Risikomodell', 'Education', 9);